import Head from 'next/head'
import Navbar from '@components/Navbar';
import { useRef } from 'react';
import Code from '@components/Code';
import { useAtom } from 'jotai';
import { fruitsAtom } from '@store/useAtom';

export default function Fruit() {

  const [fruits, setFruits] = useAtom(fruitsAtom)
  function addFruit(newFruit) {
    setFruits([...fruits, newFruit])
  }
  function removeFruit() {
    setFruits(fruits.slice(0, -1))
  }
  function removeAllFruits() {
    setFruits([])
  }
  function restoreAllFruits() {
    setFruits(['apple 🍏', 'banana 🍌', 'orange 🍊'])
  }
  const inputFruitRef = useRef()
  function handleAddFruit() {
    const value = inputFruitRef.current.value
    if (value !== "") addFruit(value)
    else alert("fruit name cannot empty !")
    inputFruitRef.current.value = "";
  }

  return (
    <>
      <Head>
        <title>Fruits Data 🍏 🍌 🍊</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold">Fruits Data 🍏 🍌 🍊</h1>

          <div className="my-8">
            <ul className="dark:text-white my-2">
              {fruits.map((fruit, index) =>
                <li key={index}>{fruit}</li>
              )}
            </ul>
            <span className="mt-2 dark:text-white">{fruits.length} fruits available</span>
            <p className="dark:text-white my-2">Add a new fruit</p>
            <div className="mb-2">
              <input ref={inputFruitRef} className="px-1.5 mr-2 h-7 border border-gray-300 dark:border-neutral-700 rounded bg-gray-100 dark:bg-neutral-800 dark:text-white focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" />
              <button onClick={handleAddFruit} className={`bg-blue-500 hover:bg-blue-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>add fruit</button>
            </div>
            <button onClick={removeFruit} className={`bg-red-500 hover:bg-red-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>remove last</button>
            <button onClick={removeAllFruits} className="bg-orange-500 hover:bg-orange-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">remove all</button>
            <button onClick={restoreAllFruits} className="bg-teal-500 hover:bg-teal-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">restore all</button>
          </div>

          <Code name="store/useAtom" code={`import { atom } from 'jotai'

export const fruitsAtom = atom(['apple 🍏', 'banana 🍌', 'orange 🍊'])`} />

          <Code name="pages/fruit" code={`import { useAtom } from 'jotai';
import { fruitsAtom } from '@store/useAtom';
import { useRef } from 'react';

export default function Fruit() {

  const [fruits, setFruits] = useAtom(fruitsAtom)
  function addFruit(newFruit) {
    setFruits([...fruits, newFruit])
  }
  function removeFruit() {
    setFruits(fruits.slice(0, -1))
  }
  function removeAllFruits() {
    setFruits([])
  }
  function restoreAllFruits() {
    setFruits(['apple 🍏', 'banana 🍌', 'orange 🍊'])
  }
  const inputFruitRef = useRef()
  function handleAddFruit() {
    const value = inputFruitRef.current.value
    if (value !== "") addFruit(value)
    else alert("fruit name cannot empty !")
    inputFruitRef.current.value = "";
  }

  return (
    <ul>
      {fruits.map((fruit, index) =>
        <li key={index}>{fruit}</li>
      )}
    </ul>
    <span>{fruits.length} fruits available</span>
    <p>Add a new fruit</p>
    <div>
      <input ref={inputFruitRef}/>
      <button onClick={handleAddFruit}>add fruit</button>
    </div>
    <button onClick={removeFruit}>remove last</button>
    <button onClick={removeAllFruits}>remove all</button>
    <button onClick={restoreAllFruits}>restore all</button>
  )
}`} />

        </div>
      </main >
    </>
  )
}
