import Head from 'next/head'
import Navbar from '@components/Navbar';
import Code from '@components/Code';
import { useAtom } from 'jotai';
import { lionAtom } from '@store/useAtom';

export default function Lion() {

  const [lion, setLion] = useAtom(lionAtom)

  return (
    <>
      <Head>
        <title>Lion Data 🦁</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold">Lion Data 🦁</h1>

          <div className="my-8">
            <p className="dark:text-white my-2">{lion} lions around here</p>
            <button onClick={() => setLion(lion + 1)} disabled={lion === 5} className={`${lion === 5 && 'cursor-not-allowed'} bg-blue-500 hover:bg-blue-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>increase</button>
            <button onClick={() => setLion(lion - 1)} disabled={lion === 0} className={`${lion === 0 && 'cursor-not-allowed'} bg-red-500 hover:bg-red-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2`}>decrease</button>
            <button onClick={() => setLion(0)} className="bg-orange-500 hover:bg-orange-600 transition-all cursor-pointer text-white rounded py-1 px-2 text-sm mr-2">remove</button>
          </div>

          <Code name="store/useAtom" code={`import { atom } from 'jotai'

export const lionAtom = atom(2)`} />

          <Code name="pages/lion" code={`import { useAtom } from 'jotai';
import { lionAtom } from '@store/useAtom';

export default function Lion() {

  const [lion, setLion] = useAtom(lionAtom)

  return (
    <p>{lion} lions around here</p>
    <button onClick={() => setLion(lion + 1)} disabled={lion === 5} className={'\${lion === 5 && 'cursor-not-allowed'} cursor-pointer'}>increase</button>
    <button onClick={() => setLion(lion - 1)} disabled={lion === 0} className={'\${lion === 0 && 'cursor-not-allowed'} cursor-pointer'}>decrease</button>
    <button onClick={() => setLion(0)}>remove</button>
  )
}`} />

        </div>
      </main >
    </>
  )
}
